; Generated by PNG2CHR Studio animation metadata v2.
.export hero_animation_sprites
.export hero_animation_frames
.export hero_animations
.export hero_animation_count

.segment "RODATA"

hero_animation_sprites:
    .byte $00, $00, $00, $00
    .byte $08, $00, $02, $00
    .byte $00, $00, $00, $00
    .byte $08, $00, $02, $40
    .byte $00, $00, $01, $00
    .byte $08, $00, $03, $00
    .byte $00, $00, $01, $80
    .byte $08, $00, $03, $40
    .byte $F8, $00, $01, $40
    .byte $F0, $00, $03, $40
    .byte $F8, $00, $01, $C0
    .byte $F0, $00, $03, $00

hero_animation_frames:
    .word 0
    .byte 2, 12
    .word 2
    .byte 2, 18
    .word 4
    .byte 2, 6
    .word 6
    .byte 2, 6
    .word 8
    .byte 2, 6
    .word 10
    .byte 2, 6

hero_animations:
    .word 0
    .byte 2, 2, 2, 0, $00
    .word 2
    .byte 2, 2, 2, 1, $02
    .word 4
    .byte 2, 2, 2, 1, $81

hero_animation_count:
    .byte 3
