; Generated by PNG2CHR Studio animation metadata v4.
.export hero_animation_sprites
.export hero_animation_frames
.export hero_animation_animations
.export hero_animation_animation_count

.segment "RODATA"

hero_animation_sprites:
    .byte $00, $00
    .word $0000
    .byte $00
    .byte $08, $00
    .word $0002
    .byte $00
    .byte $00, $00
    .word $0000
    .byte $00
    .byte $08, $00
    .word $0002
    .byte $40
    .byte $00, $00
    .word $0001
    .byte $00
    .byte $08, $00
    .word $0003
    .byte $00
    .byte $00, $00
    .word $0001
    .byte $80
    .byte $08, $00
    .word $0003
    .byte $40
    .byte $08, $00
    .word $0001
    .byte $40
    .byte $00, $00
    .word $0003
    .byte $40
    .byte $08, $00
    .word $0001
    .byte $C0
    .byte $00, $00
    .word $0003
    .byte $00

hero_animation_frames:
    .word 0
    .byte 2, 12
    .word 2
    .byte 2, 18
    .word 4
    .byte 2, 6
    .word 6
    .byte 2, 6
    .word 8
    .byte 2, 6
    .word 10
    .byte 2, 6

hero_animation_animations:
    .word 0
    .byte 2, 2, 2, 0, $00
    .word 2
    .byte 2, 2, 2, 0, $C0
    .word 4
    .byte 2, 2, 2, 0, $C0

hero_animation_animation_count:
    .byte 3
